stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar

deploy-developement:
  stage: deploy
  only:
    - develop
  script:
    - echo developement

deploy-production:
  stage: deploy
  only:
    - master
  script:
    - echo production