stages:
  - pre-notify
  - build
  - deploy
  - post-notify

variables:
  HAS_TO_BE_PUT_IN_THE_DATA: "true"
  HAS_TO_BE_PUBLISHED_INTO_ARTIFACTORY: "false"
  ARTIFACTORY_REPOSITORY: ""
  ARTIFACTORY_ARTIFACT_GROUP: ""
  ARTIFACTORY_ARTIFACT_NAME: ""
  ARTIFACTORY_ARTIFACT_VERSION: ""

pre-notify:
  stage: pre-notify
  script:
    - 'curl -k --data "status=pre&project=${CI_PROJECT_NAME}&url=${CI_PROJECT_URL}&branch=${CI_BUILD_REF_NAME}" https://blackmesa.samagames.net:3978/api/gitlab-ci'

build:
  stage: build
  script:
    - 'if [ -f "build.gradle" ]; then gradle build; else mvn install; fi'
  artifacts:
    paths:
      - build/libs/*.jar
      - target/*.jar
    expire_in: 1 day

deploy-developement:
  stage: deploy
  only:
    - develop
    - 1.10
  script:
    - 'if [ "$HAS_TO_BE_PUT_IN_THE_DATA" == "true" ]; then if [ -f "build.gradle" ]; then cp -f build/libs/*.jar /home/www/static/templates/dependencies/; else cp -f target/*.jar /home/www/static/templates/dependencies/; fi; fi'
    - 'if [ "$HAS_TO_BE_PUBLISHED_INTO_ARTIFACTORY" == "true" ]; then if [ -f "build.gradle" ]; then artifactory-publish build/libs/${ARTIFACTORY_ARTIFACT_NAME}-${ARTIFACTORY_ARTIFACT_VERSION}.jar $ARTIFACTORY_REPOSITORY $ARTIFACTORY_ARTIFACT_GROUP $ARTIFACTORY_ARTIFACT_NAME $ARTIFACTORY_ARTIFACT_VERSION; else artifactory-publish target/${ARTIFACTORY_ARTIFACT_NAME}-${ARTIFACTORY_ARTIFACT_VERSION}.jar $ARTIFACTORY_REPOSITORY $ARTIFACTORY_ARTIFACT_GROUP $ARTIFACTORY_ARTIFACT_NAME $ARTIFACTORY_ARTIFACT_VERSION; fi ; fi'

deploy-production:
  stage: deploy
  only:
    - master
  script:
    - 'if [ "$HAS_TO_BE_PUT_IN_THE_DATA" == "true" ]; then if [ -f "build.gradle" ]; then scp -prq build/libs/*.jar root@94.23.20.180:/var/www/static/templates/dependencies/; else scp -prq target/*.jar root@94.23.20.180:/var/www/static/templates/dependencies/; fi; fi'

post-notify-success:
  stage: post-notify
  script:
    - 'curl -k --data "status=post&result=success&project=${CI_PROJECT_NAME}&url=${CI_PROJECT_URL}&branch=${CI_BUILD_REF_NAME}" https://blackmesa.samagames.net:3978/api/gitlab-ci'
  when: on_success
  
post-notify-fail:
  stage: post-notify
  script:
    - 'curl -k --data "status=post&result=fail&project=${CI_PROJECT_NAME}&url=${CI_PROJECT_URL}&branch=${CI_BUILD_REF_NAME}" https://blackmesa.samagames.net:3978/api/gitlab-ci'
  when: on_failure
