name: Hub
main: net.samagames.hub.Hub
version: 1.0
authors: [BlueSlime]
website: http://samagames.net/
depend: [SamaGamesAPI]

commands:
  npc:
    description: Commandes relatives aux NPC's
    usage: /npc