name: Hub
main: net.samagames.hub.Hub
version: 5.0.0

author: BlueSlime
website: http://blueslime.fr

depend: [SamaGamesAPI, ProtocolLib, LibsDisguises, EffectLib]

commands:
  # Player commands ----------------------------
  click:
    description: Commande relative au ClickMe
    usage: /click <Joueur>
    aliases: clickme
  meh:
    description: Commande relative au Jukebox
    usage: /meh
  woot:
    description: Commande relative au Jukebox
    usage: /woot
  jukebox:
    description: Commande relative au Jukebox
    usage: /jukebox
  join:
    description: Commande relative au join des file d'attente
    usage: /join
  fly:
    description: Commande relative au Fly
    usage: /fly

  # Animating commands -------------------------
  event:
    description: Commande relative aux événements
    usage: /event

  # Moderating commands ------------------------
  pllock:
    description: Commande relative au Jukebox
    usage: /pllock
  plnext:
    description: Commande relative au Jukebox
    usage: /plnext
  plclear:
    description: Commande relative au Jukebox
    usage: /plclear
  slow:
    description: Commande relative au chat
    usage: /slow
  shutup:
    description: Commande relative au chat
    usage: /shutup

  # Admin commands -----------------------------
  npc:
    description: Commandes relatives aux NPC's
    usage: /npc
  sign:
    description: Commandes relatives aux panneaux
    usage: /sign
  anguille:
    description: Commande relative aux anguilles de Maite
    usage: /anguille
  evacuate:
    description: Commande d'évacuation
    usage: /evacuate
  pearl:
    description: Commande relative aux perles
    usage: /pearl

  # Easter Eggs --------------------------------