name: Hub
main: net.samagames.hub.Hub
version: 1.0
authors: [BlueSlime]
website: http://samagames.net/
depend: [SamaGamesAPI]

commands:
  # Player commands ----------------------------
  click:
    description: Commande relative au ClickMe
    usage: /click <Joueur>
    aliases: clickme
  meh:
    description: Commande relative au Jukebox
    usage: /meh
  woot:
    description: Commande relative au Jukebox
    usage: /woot
  jukebox:
    description: Commande relative au Jukebox
    usage: /jukebox

  # Moderating commands ------------------------
  pllock:
    description: Commande relative au Jukebox
    usage: /pllock
  plnext:
    description: Commande relative au Jukebox
    usage: /plnext
  plclear:
    description: Commande relative au Jukebox
    usage: /plclear
  slow:
    description: Commande relative au chat
    usage: /slow
  shutup:
    description: Commande relative au chat
    usage: /shutup

  # Admin commands -----------------------------
  npc:
    description: Commandes relatives aux NPC's
    usage: /npc
  sign:
    description: Commandes relatives aux panneaux
    usage: /sign
    aliases: /area
  anguille:
    description: Commande relative aux Anguilles de Maite
    usage: /anguille
    aliases: [jeanpierrecoffe, frontnational]
  nbs:
    description: Commande relative au Jukebox
    usage: /nbs
  evacuate:
    description: Commande d'évacuation
    usage: /evacuate
    aliases: [bagdad]

  # Easter Eggs --------------------------------
  pacman:
    description: Easter Egg
    usage: /pacman
