name: Hub
main: net.samagames.hub.Hub
version: 1.0
authors: [BlueSlime]
website: http://samagames.net/
depend: [SamaGamesAPI]

commands:
  # Player commands ----------------------------
  click:
    description: Commande relative au ClickMe
    usage: /click <Joueur>
    alias: /clickme
  meh:
    description: Commande relative au Jukebox
    usage: /meh
  woot:
    description: Commande relative au Jukebox
    usage: /woot

  # Admin commands -----------------------------
  npc:
    description: Commandes relatives aux NPC's
    usage: /npc
  sign:
    description: Commandes relatives aux panneaux
    usage: /sign
    alias: /area

  # Easter Eggs --------------------------------
  pacman:
    description: Easter Egg
    usage: /pacman
